--- JaVox Baker.
--- A fully compatible two-way interface to build JaVox voice packs.
---
--- How it works (or will work):
---     - You can build a voice pack with the standard interface:
---         local vp = JaVox.Baker:buildVoicePack()
---         vp:setName("Combine Soldier 2026 Pack")
---         vp:setAuthors({"Johnny Appleseed"})
---         vp:useFilesystem("combinesoldier2026") -- loads in files like actions/reload/reload1-6.wav into a nice object.
---         vp:submitToJaVox()
---
--- It can handle PVox packs as well, using the same format, and even spoofing the same PVox functions.
