-- JaVox TFA-VOX Compatibility Layer
-- Converts legacy TFA-VOX pack files into JaVox modules.

print("[JAVOX] converting tfa modules")

local MDLPRIgnore = {
    ["solo"] = true,
    ["coop"] = true,
}

local Skips = {
    ["snd1"] = true,
    ["snd2"] = true,
    ["snd3"] = true,
    ["snd4"] = true,
    ["snd5"] = true,
    ["snd6"] = true,
    ["snd7"] = true,
    ["snd8"] = true,
    ["snd9"] = true,
    ["snd10"] = true,
}

local MDLAliases = {
    ["spawn"] = "self.spawn",
    ["pickup"] = "self.pickup",

    -- TODO: should we add a self.diebyentity?
    ["death"] = "self.die",
    ["killedby"] = "self.die",

    ["noammo"] = "weaponry.out_of_ammo",
    ["reload"] = "weaponry.reload",
    ["grenadecall"] = "weaponry.frag_out",
    ["barrellcall"] = "weaponry.barrell",

    ["HITGROUP_GENERIC"] = "self.damage",
    ["HITGROUP_HEAD"] = "self.damage.head",
    ["HITGROUP_CHEST"] = "self.damage.chest",
    ["HITGROUP_STOMACH"] = "self.damage.stomach",
    ["HITGROUP_RIGHTLEG"] = "self.damage.rightleg",
    ["HITGROUP_LEFTLEG"] = "self.damage.leftleg",
    ["HITGROUP_LEFTARM"] = "self.damage.leftarm",
    ["HITGROUP_RIGHTARM"] = "self.damage.rightarm",
    ["HITGROUP_GEAR"] = "self.damage.gear",
    ["ACT_GMOD_TAUNT"] = "self.talk",
    ["crithit"] = "self.damage",
    ["murd"] = "ents.kill",
    ["spotcomb"] = "ents.spotted.npc_combine_s",
    ["spotzom"] = "ents.spotted.npc_zombie",
    ["spotgnrc"] = "ents.spotted",
}

local function slugify(name)
    if not isstring(name) then return nil end
    name = string.lower(name)
    name = string.gsub(name, "[^%w]+", "_")
    name = string.gsub(name, "_+", "_")
    name = string.gsub(name, "^_", "")
    name = string.gsub(name, "_$", "")
    return name
end

local function newModule()
    return {
        displayName = "",
        author = "TFA-VOX Generator",
        description = "Converted TFA-VOX pack for JaVox.",
        actions = { callouts = {} },
        tags = { "tfa_vox" },
        patterns = {
            -- since we gotta be a bit more string-focused when scripting audio packs with JaVox,
            -- i'm gonna do this hoping TFA-VOX has no special zombies.
            ["ents%.spotted%.npc_.*zombie"] = "ents.spotted.npc_zombie",
            ["ents%.spotted%.*"] = "ents.spotted",
            ["ents%.kill%.*"] = "ents.kill",
        }
    }
end

local ttb = newModule()

function GetAliasFor(sound_script_id)
    for k, v in pairs(MDLAliases) do
        if sound_script_id == k or string.StartsWith(sound_script_id, k) then return v end
    end
end

function TransformName(s)
    if ! s then return end
    return slugify(string.sub(s, 7))
end

function TFAVOX_GenerateSound(mdlprefix, sound_script_id, sndtable)
    if not JaVox then return end

    ttb.displayName = mdlprefix
    ttb.MDLPrefix = mdlprefix
    ttb.actions = ttb.actions or { callouts = {} }
    ttb.actions.callouts = ttb.actions.callouts or {}

    if string.StartsWith(string.lower(sound_script_id), "wheel_") then
        -- callouts
        local pref = TransformName(sound_script_id)
        if ! pref then return end

        if not ttb.actions.callouts[pref] then
            ttb.actions.callouts[pref] = {}
        end

        if not ttb.actions.callouts[pref].audioFiles then
            ttb.actions.callouts[pref].audioFiles = {}
        end
        local soundtable = ttb.actions.callouts[pref].audioFiles

        for _, v in pairs(sndtable) do
            if not Skips[v] then
                table.insert(soundtable, v)
            end
        end
    else
        local action_name = GetAliasFor(sound_script_id)
        if ! action_name then return end

        ttb.actions = ttb.actions or { callouts = {} }
        if not ttb.actions[action_name] then ttb.actions[action_name] = {} end
        if not ttb.actions[action_name].audioFiles then
            ttb.actions[action_name].audioFiles = {}
        end

        local soundtable = ttb.actions[action_name].audioFiles

        for _, v in pairs(sndtable) do
            if not Skips[v] then
                table.insert(soundtable, v)
            end
        end
    end
end

function TFAVOX_RegisterPack(mdl, pack)
    if (! isstring(pack)) then return end
    return JaVox:registerModule(mdl, pack)
end

for _, f in pairs(file.Find("lua/tfa_vox/packs/*.lua", "GAME")) do
    print("[JAVOX] found a module file " .. f)
    include("tfa_vox/packs/" .. f)

    if MDLPRIgnore[ttb.MDLPrefix] then
        ttb = {}
        continue
    end

    ---@cast ttb PlayerVoxModule

    if ttb.MDLPrefix == nil then continue end

    ttb.displayName = "TFA-Generated Module `" .. ttb.MDLPrefix .. "'"
    ttb.description = "This module was generated by PVOX+TFA-VOX Compatibility Layer."

    if ttb.actions and ttb.actions.callouts then
        ttb.callouts = ttb.callouts or {}
        for calloutname, _ in pairs(ttb.actions.callouts) do
            ttb.callouts[calloutname] = string.format("callouts.%s", calloutname)
        end
    end

    JaVox:registerModule(ttb.MDLPrefix, ttb)
    ttb = newModule()
end
